version: '3'
networks:
  local_network:
    external: true
services:
  hello:
    image: hello:1.0
    container_name: hello_1.0
    working_dir: /home
    command: ["java", "-jar", "demo-docker.jar"]
    ports:
      - 8080:8080
#    env_file:
#      - .env.test
    networks:
      - local_network

