version: '3'
networks:
  local_network:
    external: true
services:
  hello:
    image: hello:1.1
    container_name: hello_1.1
    working_dir: /home
    command: ["java", "-jar", "demo-docker.jar"]
    ports:
      - 8081:8081
#    env_file:
#      - .env
    networks:
      - local_network

